In [1]:
! pip install ftfy regex tqdm
! pip install git+https://github.com/openai/CLIP.git

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB 2.2 MB/s eta 0:00:00
  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-7h79okcx
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /tmp/pip-req-build-7h79okcx
  Resolved https://github.com/openai/CLIP.git to commit a1d071733d7111c9c014f024669f959182114e33
  Preparing metadata (setup.py) ... done
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369497 sha256=3e20bf7b56c0ac333062904117a7067d77e9f307853c3428e31ab6569f26de33
  Stored in directory: /tmp/pip-ephem-wheel-cache-9qoprhqh/wheels/da/2b/4c/d6691fa9597aac8bb85d2ac13b112deb897d5b50f5ad9a37e4
Successfully built clip


In [2]:
import numpy as np
import torch
from pkg_resources import packaging

print("Torch version:", torch.__version__)

Torch version: 2.1.0+cu121


In [3]:
import clip

clip.available_models()

['RN50',
 'RN101',
 'RN50x4',
 'RN50x16',
 'RN50x64',
 'ViT-B/32',
 'ViT-B/16',
 'ViT-L/14',
 'ViT-L/14@336px']

In [4]:
from PIL import Image
import requests

import pandas as pd

from statistics import mean
from sklearn.metrics import confusion_matrix

from transformers import CLIPProcessor, CLIPModel

allergens = {
    0: "gluten",
    1: "eggs",
    2: "milk",
    3: "nuts",
    4: "peanuts",
    5: "soja",
    6: "molluscs",
    7: "fish",
    8: "lupin",
    9: "crustaceans",
    10: "sesame",
    11: "mustard",
    12: "celery",
    13: "sulphites"
}

nb_allergens = len(allergens)

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

def predict(image, allergen):
    image = Image.open(image)
    match allergen:
        case 0:
            inputs = processor(text=["ingredient list of a product containing wheat or gluten", "ingredient list of a product without wheat nor gluten"], images=image, return_tensors="pt", padding=True)
        case 1:
            inputs = processor(text=["ingredient list of a product containing eggs", "ingredient list of a product without eggs"], images=image, return_tensors="pt", padding=True)
        case 2:
            inputs = processor(text=["ingredient list of a product containing milk", "ingredient list of a product without milk"], images=image, return_tensors="pt", padding=True)
        case 3:
            inputs = processor(text=["ingredient list of a product containing nuts", "ingredient list of a product without nuts"], images=image, return_tensors="pt", padding=True)
        case 4:
            inputs = processor(text=["ingredient list of a product containing peanuts", "ingredient list of a product without peanuts"], images=image, return_tensors="pt", padding=True)
        case 5:
            inputs = processor(text=["ingredient list of a product containing soya", "ingredient list of a product without soya"], images=image, return_tensors="pt", padding=True)
        case 6:
            inputs = processor(text=["ingredient list of a product containing molluscs", "ingredient list of a product without molluscs"], images=image, return_tensors="pt", padding=True)
        case 7:
            inputs = processor(text=["ingredient list of a product containing fish", "ingredient list of a product without fish"], images=image, return_tensors="pt", padding=True)
        case 8:
            inputs = processor(text=["ingredient list of a product containing lupin", "ingredient list of a product without lupin"], images=image, return_tensors="pt", padding=True)
        case 9:
            inputs = processor(text=["ingredient list of a product containing crustaceans", "ingredient list of a product without crustaceans"], images=image, return_tensors="pt", padding=True)
        case 10:
            inputs = processor(text=["ingredient list of a product containing sesame", "ingredient list of a product without sesame"], images=image, return_tensors="pt", padding=True)
        case 11:
            inputs = processor(text=["ingredient list of a product containing mustard", "ingredient list of a product without mustard"], images=image, return_tensors="pt", padding=True)
        case 12:
            inputs = processor(text=["ingredient list of a product containing celery", "ingredient list of a product without celery"], images=image, return_tensors="pt", padding=True)
        case 13:
            inputs = processor(text=["ingredient list of a product containing sulphites", "ingredient list of a product without sulphites"], images=image, return_tensors="pt", padding=True)

    outputs = model(**inputs)
    logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
    probs = logits_per_image.softmax(dim=1)  # we can take the softmax to get the label probabilities

    return probs[0][0].item()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/4.19k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/568 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [17]:
from google.colab import files
data_to_load = files.upload()
import io

Saving labellisation(1).xlsx to labellisation(1).xlsx


In [92]:
df = pd.read_excel('/content/labellisation(1).xlsx')

In [93]:
df

Name  gluten  egg  milk  nuts  peanuts  soya  molluscs  fish  lupin  \
0    001.png       1    1     1     1        0     1         0     0      0   
1    002.png       1    1     1     1        0     1         0     0      0   
2    003.png       1    1     1     1        0     1         0     0      0   
3    004.png       1    1     1     1        0     1         0     0      0   
4    005.png       1    1     1     1        0     1         0     0      0   
..       ...     ...  ...   ...   ...      ...   ...       ...   ...    ...   
214  218.png       0    0     1     0        0     1         0     0      0   
215  219.png       1    0     1     1        0     1         0     0      0   
216  220.png       0    0     0     0        0     0         0     0      0   
217  221.png       0    0     0     0        0     0         0     0      0   
218  222.png       0    0     0     0        0     1         0     0      0   

     crustaceans  sesame  mustard  celery  sulphites  
0              0       0        0       0          1  
1              0       0        0       0          0  
2              0       0        0       0          0  
3              0       0        0       0          0  
4              0       0        0       0          0  
..           ...     ...      ...     ...        ...  
214            0       0        0       0          0  
215            0       0        0       0          0  
216            0       0        0       0          0  
217            0       0        0       0          0  
218            0       0        0       0          0  

[219 rows x 15 columns]

In [94]:
df = df.drop('Name',axis='columns')

In [89]:
results = pd.DataFrame()
for image in range(1, 26):
  prediction_array = []
  for allergen in range(0, 14):
            prediction_array.append(predict(f"{image:03d}.jpg", allergen))
  results = results.append(pd.Series(prediction_array, name=f"{image}"))

<ipython-input-89-156f4993bc32>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append(pd.Series(prediction_array, name=f"{image}"))
<ipython-input-89-156f4993bc32>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append(pd.Series(prediction_array, name=f"{image}"))
<ipython-input-89-156f4993bc32>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append(pd.Series(prediction_array, name=f"{image}"))
<ipython-input-89-156f4993bc32>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append(pd.Series(prediction_array, name=f"{image}"))
<ipython-input-89-156f4993bc32>:6: F

In [90]:
results

0         1         2         3         4         5         6   \
1   0.385675  0.169330  0.116219  0.183452  0.226653  0.266286  0.275411   
2   0.148237  0.059192  0.061426  0.166475  0.146269  0.175701  0.183528   
3   0.648850  0.418871  0.439551  0.512278  0.496981  0.513282  0.268096   
4   0.616585  0.462122  0.387110  0.413479  0.454868  0.481388  0.172065   
5   0.652801  0.566827  0.309575  0.413311  0.495627  0.549897  0.261522   
6   0.598222  0.310715  0.341645  0.568229  0.542188  0.569838  0.305233   
7   0.644125  0.408602  0.520943  0.566269  0.523919  0.538450  0.318007   
8   0.747746  0.412236  0.421118  0.610082  0.682561  0.729461  0.516928   
9   0.470145  0.186853  0.219079  0.281396  0.172775  0.140549  0.105025   
10  0.361524  0.227028  0.225409  0.237138  0.269106  0.223375  0.146723   
11  0.544209  0.219721  0.202943  0.287774  0.171645  0.228702  0.250108   
12  0.360804  0.154812  0.280133  0.280633  0.299121  0.261684  0.155739   
13  0.405213  0.153782  0.193690  0.232630  0.263143  0.150875  0.103764   
14  0.576282  0.231164  0.264673  0.185235  0.179562  0.277992  0.181126   
15  0.442888  0.279062  0.280926  0.308365  0.247906  0.299579  0.190768   
16  0.458150  0.140066  0.318784  0.412506  0.371260  0.161388  0.119253   
17  0.584139  0.275168  0.568943  0.350745  0.321492  0.369168  0.159835   
18  0.480223  0.105216  0.342307  0.278752  0.219894  0.251676  0.111679   
19  0.237567  0.080103  0.169008  0.095227  0.112009  0.061429  0.091929   
20  0.442687  0.219702  0.394433  0.401184  0.425525  0.396023  0.185455   
21  0.287106  0.105161  0.163474  0.252457  0.295038  0.239585  0.108321   
22  0.421243  0.260554  0.255597  0.383242  0.369749  0.254728  0.115685   
23  0.479457  0.314921  0.304746  0.327739  0.348426  0.275960  0.124554   
24  0.582742  0.046101  0.120520  0.239705  0.230971  0.262857  0.118254   
25  0.516771  0.165697  0.240566  0.296131  0.429388  0.238487  0.152606   

          7         8         9         10        11        12        13  
1   0.274487  0.140998  0.354353  0.185925  0.290245  0.240427  0.108279  
2   0.148582  0.093173  0.367541  0.204503  0.238817  0.147976  0.078033  
3   0.435636  0.352049  0.549944  0.429893  0.867408  0.422417  0.499638  
4   0.350708  0.229586  0.436330  0.323600  0.839013  0.441960  0.359433  
5   0.454334  0.292942  0.519908  0.371429  0.820597  0.378328  0.501480  
6   0.438546  0.318808  0.492714  0.524051  0.499279  0.487392  0.302480  
7   0.377179  0.339792  0.468114  0.584212  0.540777  0.495354  0.267676  
8   0.503382  0.542832  0.619900  0.719594  0.695006  0.633377  0.410886  
9   0.267699  0.030324  0.355000  0.227147  0.314646  0.178532  0.036018  
10  0.189395  0.089700  0.307218  0.185645  0.291566  0.109507  0.121369  
11  0.474731  0.105259  0.336831  0.173712  0.193273  0.219990  0.092020  
12  0.291965  0.119520  0.323827  0.313512  0.269453  0.278896  0.142162  
13  0.299372  0.047904  0.267505  0.194934  0.198067  0.193342  0.066909  
14  0.522848  0.062804  0.410036  0.289223  0.375442  0.235061  0.141589  
15  0.448901  0.162043  0.428079  0.295727  0.339406  0.321668  0.183865  
16  0.271348  0.076056  0.401617  0.270691  0.519462  0.351813  0.070475  
17  0.331029  0.140445  0.420806  0.486961  0.430521  0.365707  0.147958  
18  0.228074  0.089472  0.300301  0.255048  0.213030  0.245042  0.078430  
19  0.102273  0.038434  0.188168  0.147144  0.124328  0.096983  0.035226  
20  0.325269  0.141762  0.326341  0.426942  0.385349  0.276691  0.288121  
21  0.250690  0.052748  0.261957  0.254068  0.269972  0.210239  0.083551  
22  0.352210  0.065958  0.391842  0.383548  0.699961  0.313156  0.106460  
23  0.292028  0.117554  0.307835  0.214400  0.671787  0.237706  0.255077  
24  0.128433  0.082723  0.214386  0.289469  0.223613  0.171103  0.103077  
25  0.342412  0.108773  0.449758  0.309269  0.629281  0.330890  0.107427

In [95]:
df = df.iloc[:25,:]
df

gluten  egg  milk  nuts  peanuts  soya  molluscs  fish  lupin  \
0        1    1     1     1        0     1         0     0      0   
1        1    1     1     1        0     1         0     0      0   
2        1    1     1     1        0     1         0     0      0   
3        1    1     1     1        0     1         0     0      0   
4        1    1     1     1        0     1         0     0      0   
5        0    0     1     1        0     1         0     0      0   
6        0    0     1     1        0     1         0     0      0   
7        0    0     1     1        0     1         0     0      0   
8        1    1     1     1        0     1         0     0      0   
9        1    1     1     1        0     0         0     0      0   
10       1    1     1     1        0     0         0     0      0   
11       1    0     1     0        0     1         0     0      0   
12       1    0     1     0        0     1         0     0      0   
13       1    0     1     1        0     0         0     0      0   
14       1    0     1     1        1     1         0     0      0   
15       1    0     1     0        0     1         0     0      0   
16       1    0     1     0        0     1         0     0      0   
17       1    0     1     0        0     1         0     0      0   
18       1    0     1     0        0     1         0     0      0   
19       1    0     1     0        0     0         0     0      0   
20       1    0     1     0        0     0         0     0      0   
21       1    1     1     0        0     1         0     0      0   
22       1    1     1     0        0     1         0     0      0   
23       0    0     0     1        1     0         0     0      0   
24       1    0     1     0        0     1         0     0      0   

    crustaceans  sesame  mustard  celery  sulphites  
0             0       0        0       0          1  
1             0       0        0       0          0  
2             0       0        0       0          0  
3             0       0        0       0          0  
4             0       0        0       0          0  
5             0       0        0       0          0  
6             0       0        0       0          0  
7             0       0        0       0          0  
8             0       0        0       0          0  
9             0       0        0       0          0  
10            0       0        0       0          0  
11            0       0        0       0          0  
12            0       0        0       0          0  
13            0       0        0       0          0  
14            0       0        0       0          0  
15            0       0        0       0          0  
16            0       0        0       0          0  
17            0       0        1       0          0  
18            0       0        0       0          0  
19            0       1        0       0          0  
20            0       1        0       0          0  
21            0       0        0       0          1  
22            0       0        0       0          1  
23            0       0        0       0          0  
24            0       0        0       0          0

gluten

In [96]:
confusion_matrix(results.iloc[:, 0].round(),df['gluten'],labels=[1,0])

array([[ 7,  4],
       [14,  0]])

egg

In [97]:
confusion_matrix(results.iloc[:, 1].round(),df['egg'],labels=[1,0])

array([[ 1,  0],
       [ 9, 15]])

milk

In [98]:
confusion_matrix(results.iloc[:, 2].round(),df['milk'],labels=[1,0])

array([[ 2,  0],
       [22,  1]])

nuts

In [99]:
confusion_matrix(results.iloc[:, 3].round(),df['nuts'],labels=[1,0])

array([[ 4,  0],
       [10, 11]])

peanuts

In [100]:
confusion_matrix(results.iloc[:, 4].round(),df['peanuts'],labels=[1,0])

array([[ 0,  3],
       [ 2, 20]])

soya

In [101]:
confusion_matrix(results.iloc[:, 5].round(),df['soya'],labels=[1,0])

array([[ 5,  0],
       [14,  6]])

molluscs

In [102]:
confusion_matrix(results.iloc[:, 5].round(),df['molluscs'],labels=[1,0])

array([[ 0,  5],
       [ 0, 20]])

fish

In [103]:
confusion_matrix(results.iloc[:, 6].round(),df['fish'],labels=[1,0])

array([[ 0,  1],
       [ 0, 24]])

lupin

In [104]:
confusion_matrix(results.iloc[:, 7].round(),df['lupin'],labels=[1,0])

array([[ 0,  2],
       [ 0, 23]])

crustaceans

In [105]:
confusion_matrix(results.iloc[:, 8].round(),df['crustaceans'],labels=[1,0])

array([[ 0,  1],
       [ 0, 24]])

sesame

In [106]:
confusion_matrix(results.iloc[:, 9].round(),df['sesame'],labels=[1,0])

array([[ 0,  3],
       [ 2, 20]])

mustard

In [107]:
confusion_matrix(results.iloc[:, 10].round(),df['mustard'],labels=[1,0])

array([[ 0,  3],
       [ 1, 21]])

celery

In [108]:
confusion_matrix(results.iloc[:, 11].round(),df['celery'],labels=[1,0])

array([[ 0,  9],
       [ 0, 16]])

sulphites

In [109]:
confusion_matrix(results.iloc[:, 12].round(),df['sulphites'],labels=[1,0])

array([[ 0,  1],
       [ 3, 21]])